# Generated by Django 4.1.7 on 2023-03-16 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asistente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_asistente', models.CharField(max_length=50)),
                ('telefono', models.IntegerField(blank=True, max_length=9)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_carrera', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ponente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_ponente', models.CharField(max_length=50)),
                ('telefono', models.IntegerField(blank=True, max_length=9, null=True)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoAsistente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=50)),
                ('telefono', models.IntegerField(blank=True, max_length=9)),
                ('email', models.EmailField(max_length=254)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.rol')),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_evento', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('asistente', models.ManyToManyField(to='mysite.asistente')),
                ('carrera', models.ManyToManyField(blank=True, to='mysite.carrera')),
                ('ponente', models.ManyToManyField(to='mysite.ponente')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='asistente',
            name='carrera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.carrera'),
        ),
        migrations.AddField(
            model_name='asistente',
            name='tipo_asistente',
            field=models.ForeignKey(on_delete=models.SET('Default'), to='mysite.tipoasistente'),
        ),
    ]
