# Generated by Django 4.1.7 on 2023-03-16 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistente',
            name='telefono',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='ponente',
            name='telefono',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.IntegerField(blank=True),
        ),
    ]
