# Generated by Django 4.1.7 on 2023-03-20 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistente',
            name='codigo',
            field=models.CharField(default='', max_length=9),
        ),
        migrations.AddField(
            model_name='usuario',
            name='codigo',
            field=models.CharField(default='', max_length=9),
        ),
    ]
